### ISSUE TITLE
Wrong wpa-supplicant.conf name

### ISSUE THREAD

**Issue by futurecyclist** [okyeron/fates#3]
There is a mistake in
https://github.com/okyeron/fates/blob/master/install/norns/Norns_install_instructions_1.8.md

```
Next create a wpa-supplicant.conf file with your local wifi network settings. Change the country, router name, and key in the example below.
```
Instead of ```wpa-supplicant.conf``` should be ```wpa_supplicant.conf```

**Comment by okyeron** [comment]
Fixed
