### ISSUE TITLE
Where can I get a PCB?

### ISSUE THREAD

**Issue by sunflowr** [okyeron/fates#5]
I can't seem to find any PCBs for sale anywhere. Is there a list of where to buy it?

Also, is the design files for the PCB available?
Just thinking that if it's not available for ordering, maybe it would be possible for me to manufacture a PCB myself through one of the online PCB manufacturers?

**Comment by okyeron** [comment]
Hi Johan,

Unfortunately PCBs have only be available through me and are sold out. I may have one or two left in a bin... email me from my shop <https://denki-oto.weebly.com> and we can figure something out.

Also unfortunately, due to various circumstances the designs will not be released
